name: 'Prow ChatOps'
description: 'Run ChatOps on PRs similar to prow through github actions'
inputs:
  githubevent:
    description: 'add github.event here to send the payload'
    required: true
    default: ""
  whitelist:  # list of commands to allow
    description: 'comma separated list of commands to specifically allow, empty to allow all (default).'
    required: false
    default: ''
  blacklist:
    description: 'comma separated list of commands to specifically disallow, empty to not block any (default)'
    required: false
    default: ''
#    TODO custom Word/Action?
outputs:
  chatops-list: # id of output
    description: 'The list of allowed commands to trigger chatops events'
runs:
  using: 'docker'
  image: 'Dockerfile'
#  args:
#    - ${{ inputs.whitelist }}
#    - ${{ inputs.blacklist }}
