name: Pull Request Comment
on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  react-to-comment:
    runs-on: ubuntu-latest
    steps:
      - id: setevent
        run: |
          echo "##[set-output name=event;] ${{toJson(github.event)}}"
      - name: Check Comment
        uses: Benbentwo-Sandbox/prow-chatops@master
        with:
          githubevent: '${{steps.setevent.outputs.event}}'