name: On Push
on: [push]

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
      - name: Mask fruit
        uses: Benbentwo-Sandbox/prow-chatops@master
        with:
          fruit: banana
      - name: Echo fruit
        run: echo "apple, banana, and orange"